### ISSUE TITLE
TODO: Movie Database TV Agent

### ISSUE THREAD

**Issue by sander1** [plexinc-agents/TheMovieDB.bundle#17]
- [x] No banner art available, maybe grab some from a different source? -- Combined with TVDB and/or Fanart.tv agents (as secondary agents) we can have it all, banners included.
- [x] Shows with (US) or (UK) in the filename fail, e.g. The Office (US) -- Fixed by stripping this from the search query
- [x] ~~episode.thumbs not working?~~ TMDB just doesn't have that many episode stills (yet).
- [x] ~~Move duplicate code (from Movies and TV Agent) into separate functions~~~-- Not worth it currently
- [ ] Season summary not showing, ~~but available in PMS XML~~ After checking again, the season summary does not show up in the PMS XML.
- [ ] Date based shows could be an issue, because The Movie Database is not using years for season, but normal "Season 1", "Season 2", etc. numbering.

**Comment by maxGreenblatt** [comment]
Pretty sure TMDb works as a TV agent now. Closing.
